const tweets = [
  {
    id: 1,
    person: "Ezgi Cacık",
    kullanici: "ezgicacik",
    personPhoto: "https://example.com/profile1.jpg",
    content: "Bu kediler çok tatlı",
    photo: "https://example.com/cat1.jpg",
  },
  {
    id: 2,
    person: "Ali Yılmaz",
    kullanici: "aliyilmaz",
    personPhoto: "https://example.com/profile2.jpg",
    content: "Bugün hava çok güzel",
    photo: "https://example.com/weather.jpg",
  },
  {
    id: 3,
    person: "Ayşe Kaya",
    kullanici: "aysekaya",
    personPhoto: "https://example.com/profile3.jpg",
    content: "Yeni bir kitap okuyorum",
    photo: "https://example.com/book.jpg",
  },
  {
    id: 4,
    person: "Mehmet Demir",
    kullanici: "mehmetdemir",
    personPhoto: "https://example.com/profile4.jpg",
    content: "Yürüyüş yapmak harika",
    photo: "https://example.com/walk.jpg",
  },
  {
    id: 5,
    person: "Zeynep Aydın",
    kullanici: "zeynepaydin",
    personPhoto: "https://example.com/profile5.jpg",
    content: "Yeni tarif denedim",
    photo: "https://example.com/recipe.jpg",
  },
  {
    id: 6,
    person: "Ahmet Çelik",
    kullanici: "ahmetcelik",
    personPhoto: "https://example.com/profile6.jpg",
    content: "Teknoloji hızla gelişiyor",
    photo: "https://example.com/technology.jpg",
  },
  {
    id: 7,
    person: "Fatma Yıldız",
    kullanici: "fatmayildiz",
    personPhoto: "https://example.com/profile7.jpg",
    content: "Doğada olmak huzur verici",
    photo: "https://example.com/nature.jpg",
  },
  {
    id: 8,
    person: "Mustafa Şahin",
    kullanici: "mustafasahin",
    personPhoto: "https://example.com/profile8.jpg",
    content: "Kahve içmeden güne başlayamıyorum",
    photo: "https://example.com/coffee.jpg",
  },
  {
    id: 9,
    person: "Emine Ak",
    kullanici: "emineak",
    personPhoto: "https://example.com/profile9.jpg",
    content: "Yeni müzik albümü çıktı",
    photo: "https://example.com/music.jpg",
  },
  {
    id: 10,
    person: "Hakan Öz",
    kullanici: "hakanoz",
    personPhoto: "https://example.com/profile10.jpg",
    content: "Spor yapmak enerjimi artırıyor",
    photo: "https://example.com/sport.jpg",
  },
];

export default tweets;
